apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-nodejs-service
  title: Project_Practice Node.js Service
  description: Template to create a basic Node.js backend service
spec:
  owner: user:guest
  type: service

  parameters:

    - title: Fill in some steps
      required:
        -name
      properties:
        name: 
          title: projectName
          type: string
          description: What’s the name of your project?
          ui:autofocus: true
          ui:options:
            rows: 5

    - title: Choose a Location
      required:
        -description
      properties:
    - name: description
      description: Brief description of your project
      required: false
    - name: owner
      description: Who owns this project?
      required: true

  steps:
    - id: fetch-template
      name: Fetch template files
      action: fetch:template
      input:
        url: https://github.com/Meghana-shetty/Cafe_static_copy/tree/main/Backstage_Meghana/cafe-static-website
        targetPath: ./

    - id: publish-repo
      name: Create GitHub repository and push code
      action: github:repo:push
      input:
        repoUrl: github.com?owner=Meghana-shetty&repo=${{ parameters.projectName }}
        defaultBranch: main
        description: ${{ parameters.description }}
        protectDefaultBranch: true

    - id: register-component
      name: Register component in Backstage catalog
      action: catalog:register
      input:
        repoContentsUrl: https://github.com/Meghana-shetty/${{ parameters.projectName }}
        catalogInfoPath: catalog-info.yaml
