apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-new-github-repo-from-url
  title: Create new GitHub Repo from URL
  description: Scaffold a new GitHub repo by cloning files from a source GitHub URL
  tags:
    - github
    - repo
spec:
  parameters:
    - title: GitHub source repo URL
      description: URL of the existing GitHub repo to clone files from
      type: string
      name: sourceRepoUrl
    - title: New GitHub repo name
      description: Name of the new GitHub repo to create
      type: string
      name: newRepoName
    - title: GitHub owner
      description: Owner or organization of the new repo
      type: string
      name: newRepoOwner
  steps:
    - id: fetch-source
      name: Fetch source repository
      action: fetch:template
      input:
        url: '{{ parameters.sourceRepoUrl }}'
        targetPath: './template-source'

    - id: create-repo
      name: Create new GitHub repository
      action: github:create-repo
      input:
        repoName: '{{ parameters.newRepoName }}'
        repoVisibility: 'public'
        owner: '{{ parameters.newRepoOwner }}'

    - id: publish-to-new-repo
      name: Push files to new repository
      action: github:publish
      input:
        repoUrl: 'https://github.com/{{ parameters.newRepoOwner }}/{{ parameters.newRepoName }}.git'
        directory: './template-source'
        accessToken: ${{ secrets.GITHUB_TOKEN }}
