apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-nodejs-service
  title: Project_Practice Node.js Service
  description: Template to create a basic Node.js backend service
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Fill in project details
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Project Name
          type: string
          description: What’s the name of your project?
          ui:autofocus: true

        description:
          title: Project Description
          type: string
          description: Brief description of your project

        owner:
          title: Owner
          type: string
          description: Who owns this project?

    - title: Choose a location for the new repo
      required: []
      properties: {}

  steps:
    - id: fetch-template
      name: Fetch template files
      action: fetch:template
      input:
        url: https://github.com/Meghana-shetty/Cafe_static_copy/tree/main/Backstage_Meghana/cafe-static-website
        targetPath: .

    - id: publish-repo
      name: Create GitHub repository and push code
      action: github:repo:push
      input:
        repoUrl: github.com?owner=Meghana-shetty&repo=${{ parameters.name }}
        defaultBranch: main
        description: ${{ parameters.description }}
        protectDefaultBranch: true

    - id: register-component
      name: Register component in Backstage catalog
      action: catalog:register
      input:
        repoContentsUrl: https://github.com/Meghana-shetty/${{ parameters.name }}
        catalogInfoPath: catalog-info.yaml
