apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-nodejs-service
  title: Project_Practice Node.js Service
  description: Template to create a basic Node.js backend service
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Fill in project details
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Project Name
          type: string
          description: What’s the name of your project?
          ui:autofocus: true

        description:
          title: Project Description
          type: string
          description: Brief description of your project

        owner:
          title: Owner
          type: string
          description: Who owns this project?

  steps:
    # - id: create-repo
    #   name: Create new GitHub repo
    #   action: github:create-repo
    #   input:
    #     repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.name }}
    #     description: ${{ parameters.description }}
    #     repoVisibility: public
   - id: fetchBase
     name: Fetch Base
     action: fetch:template
     input:
        url: ./skeleton
        cookiecutterCompat: true
        values:
    
    - id: fetch-template
      name: Fetch template files
      action: fetch:template
      input:
        url: https://github.com/Meghana-shetty/Cafe_static_copy/tree/main/Backstage_Meghana/cafe-static-website
        targetPath: .
    
    - id: push-to-repo
      name: Push code to GitHub
      action: github:push
      input:
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.name }}
        defaultBranch: main

    # - id: register-component
    #   name: Register component in Backstage catalog
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: https://github.com/${{ parameters.owner }}/${{ parameters.name }}
    #     catalogInfoPath: catalog-info.yaml
